spring.application.name=masterclass-back
spring.datasource.url=jdbc:mariadb://localhost:3306/masterclassdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl