spring.application.name=masterclass-back
spring.datasource.url=jdbc:mariadb://localhost:3306/masterclassdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql,classpath:shema1-1.sql
spring.sql.init.data-locations=classpath:import.sql
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fil.masterclass@gmail.com
spring.mail.password=saaw hipt qiev lkyf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.cors.allowed-origins=http://localhost:5173
